name: first

on: 
    push:
        branches:
                -   main
    pull_request:
        branches:
                -   main

jobs: 
    job1:  
        name: Fecha Ubuntu
        runs-on: ubuntu-latest
        steps:
        -   name: Step two
            uses: date

    job2:  
        name: Fecha Windows
        runs-on: windows-latest
        steps:
        -   name: Step two
            uses: "Get-Date"

    job3:  
        name: Fecha MacOS
        runs-on: macos-latest
        steps:
        -   name: Step two
            uses: date

    job4:
        needs: [job1, job2, job3] 
        name: Dependencia
        runs-on: ubuntu-lates
        steps:
        -   name: Step two
            uses: date